version: "3.9"

services:
  jenkins:
    build: .
    ports:
      - 9999:8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  
volumes:
    jenkins_home: